language: java
script: mvn clean install
deploy:
  provider: heroku
  api_key:
    secure: gjNTdSCL1aeEcjeXyvcoxaWJqWajsplfVgIRYKi9D/p4zBdiKY1fYCbipNpPkizc971G20t5uemEz8EITUc56EeDnWsj0XFlvou2Xh7lr2edy/dp1JwNO18/UewR5+6RXGYnL5yOG1PJgtqzHapwotJOrIV7LKqhCQtTC2mVrY46Ux1tAh9K6672nChE25BkSP2TyPqc6GINTzcyz7f9LGqFLw5WR2uDsK0fuGm2UhGumXG1NxImgKozFQydvv4bi9P2Xcaf3SKl91U7ylg9NORGpZ96wnqA5RIOYO2Kk6M93kpd0MA7HbHAz+HcYxe+VIZn5OrOFKt0GFKJAuiv+n46x05ZFJ4dWsXQ5kaSKBvlNAa+fjxcBkoATX5MTRUWNe0vu64+1y9CY4ysZHcwCagUyIBK0CNnySW+G+WgMKxWyryGHfTv5jwfzN8Jqyvan3rBHaKLq8wrRFB61b9qOFjWmwu0zoGI/3rkLrjA6W3wOj08y9S9cfSMlzbi1aiQKEDrysUE+GWq7FQAGEJrTWKlCqSTwUchEajiP1XxE/vkDYm7xgRppR93Umv2wK0Ms/4VobF31qbj2HU35bIXLMhOtrTTcefvEB360qs4cj+DbREwi0lLd2RcMCHLhsOzHgebUEA2yC/E1kp/ELBecxAvRrFXyAzzI1jzOO43vTk=
  app: projekt-pik