language: java
script: mvn clean install
deploy:
  provider: heroku
  api_key:
    secure: EPjC5GeRWtyp8FvFWkuX0Nh2ploOwapWeByY3WAQRc+XpyMmvx3JtVYhTRR4BvT9CDytaAB76sOmkXWlstiZg7Cokrrfoj8t3i+XQIz079+5cWH5UGBHOnxoEsJmMDglxXk4dZM0dYuVTBDH1jSxDP8yn4W6JQz+PshGBB/0YgWOuEFUo6rRaBG1ykU5TGe3HY8jozSN0Rht4dM/jBraD3P+nKwUIOcMYsiFvrgAdomKh4MAAiXqCE3NseFQvJV+zZpHatgN9+reRT4xIYl20FEcow/4IdzoDeiUlW+Avm2kLKGfB/9kOdJNJJ/1JqyOCvxAr9ZZFbIYnoEjGBMIGqKAtS7Lo+kme5QmI361iNdCx0WTgIj8uyd9Wb6dncmgORQGEXhr6HxyHWgo1eT64oBB3wUPwefcjb3iZ69etM6YqpJg4+DW0kZ9nyYbTRMrhOtEmaRseTQctxYqBud03np/r9zjEFrV5AYcYsQ4GDlTBkja8b70zsu6aZQ56G3iztbKGPEZzRF1q+bVsjZ8wSOahGQBq7fBJP5Wrdym30O9twY93LqJjuQEs5YPQNWCllMbv78jQB5KPoMvPux6r8FaBHoNh5LMCksg2Dyjbu0qP1Ba9RlXdLtEhey5xP3B49bMe6eP+A4VIKV9x1+gMy0yTYKZz0K/MUr0JJkR4F4=
  app: projekt-pik