language: java
branches:
  only:
    - develop
deploy:
    provider: heroku
  api_key:
    secure: "gZV1Bcn7Ob3PiPQwxhaXhGhW28lpHvT3TWv1EGJzijE3HXxvAJf4NwFa5o3t8yjkGPNC3XxctGH1LHzocyhinfgGgrg89eNKjWWF+6HTrwFBZNK1YbMLFtNSBiREA34qnIfHdIIHSvQwfJ0jNJHLw8OzmaA/6wetJFdOiHzMRIGx3y2axu4Du26rTJPSdYoUMLaqQ6p+bY7GRUNEqdhxPkYlk0OroTRpGPH4AJR9pMZp/ewnh1o9ptWT6YN71E4MY9UyAhMpMU0KmvrP9B/jOwui5fO8DaDu5GJt1T58STMoFAas1MIAdmy6h+8No7uuLtQUZpzDPO/9q5QnXZ1gaUol3pPgP9DyGklTBymsjIXvANHlTAmtsAjUxQtj84UNFPwN/4XPirLNxmIu4PTQdFjcf0NortwyiEn5jw/qfuVE2pRKfZDq3xGSePFqjbxUdbdDHtfxMcWCBoYO6LfXsLtsUn6rVzXT8Wp8QCBRBc4WskVmXJ3nGVc4MZxIZKQvnZPrDDqQF2Y3i7lJl44woxoVzMHGGdyUFT2idGHtH1jIwoROUlqlZn2hQynYD+XM6tDkcQ8VGQRZX1HDnij+ufGVFjRXqoRkmZ3j/UAuRTlw5APpXTM9Onye6+BwPHqQc1EmUEbHnL2FdB72lha7X0GQj85bvXqeExuE7oUZo6s="